### ISSUE TITLE
The API is returning error 404 

### ISSUE THREAD

**Issue by luizalbertobm** [shaunlaughey/supercoolapitest#4]
When I run the client application using Vagrant the server return me 404 (not found).
I do the same using Postman and Postman show the same problem.
![Captura de tela de 2021-02-21 17-44-11](https://user-images.githubusercontent.com/3503723/108633622-1a834580-746d-11eb-8005-66b85718daf4.png)

**Comment by shaunlaughey** [comment]
Switching to nginx seems to have fixed that.
