### ISSUE TITLE
It was not possible to become "www-data" user

### ISSUE THREAD

**Issue by luizalbertobm** [shaunlaughey/supercoolapitest#5]
![Captura de tela de 2021-02-21 17-50-35](https://user-images.githubusercontent.com/3503723/108633738-c4fb6880-746d-11eb-9ec4-267ce1b45a98.png)

**Comment by shaunlaughey** [comment]
Good spot I'll add instructions on replacing nologin with /bin/bash to www-data in /etc/passwd
